/**
 * Aura class name generator for DaisyUI 5.6.
 *
 * Aura is a border light effect that wraps around any component. The effect is
 * always animating by default ; pass `trigger: 'hover'` to only light it up on
 * hover (the gate is built on top of the DaisyUI classes, see the component).
 *
 * @module themes/effects/aura
 * @see https://daisyui.com/components/aura
 */

import cn from '../helpers/cn' ;

import { LG, MD, SM, XL, XS } from '../sizing/sizes' ;

// Variants (styles)

/**
 * @typedef {'dual' | 'rainbow' | 'holo' | 'gold' | 'silver' | 'glow'} AuraVariant
 */

export const DUAL    = 'dual' ;
export const RAINBOW = 'rainbow' ;
export const HOLO    = 'holo' ;
export const GOLD    = 'gold' ;
export const SILVER  = 'silver' ;
export const GLOW    = 'glow' ;

/**
 * Valid aura variants.
 * @type {AuraVariant[]}
 */
export const variants = [ DUAL, RAINBOW, HOLO, GOLD, SILVER, GLOW ] ;

const variantMap =
{
    [ DUAL    ] : 'aura-dual',
    [ RAINBOW ] : 'aura-rainbow',
    [ HOLO    ] : 'aura-holo',
    [ GOLD    ] : 'aura-gold',
    [ SILVER  ] : 'aura-silver',
    [ GLOW    ] : 'aura-glow',
} ;

// Sizes

/**
 * @typedef {'xs' | 'sm' | 'md' | 'lg' | 'xl'} AuraSize
 */

/**
 * Valid aura sizes.
 * @type {AuraSize[]}
 */
export const sizes = [ XS, SM, MD, LG, XL ] ;

const sizeMap =
{
    [ XS ] : 'aura-xs',
    [ SM ] : 'aura-sm',
    [ MD ] : 'aura-md',
    [ LG ] : 'aura-lg',
    [ XL ] : 'aura-xl',
} ;

// Triggers

/**
 * @typedef {'always' | 'hover'} AuraTrigger
 */

export const ALWAYS = 'always' ;
export const HOVER  = 'hover' ;

/**
 * Valid aura triggers.
 * @type {AuraTrigger[]}
 */
export const triggers = [ ALWAYS, HOVER ] ;

export const AURA = 'aura' ;

/**
 * Pauses the rotation animation (rest state of the `hover` trigger).
 * @type {string}
 */
export const AURA_PAUSED = '[animation-play-state:paused]' ;

/**
 * Resumes the rotation animation on hover (`hover` trigger).
 * @type {string}
 */
export const AURA_RUNNING = 'hover:[animation-play-state:running]' ;

/**
 * Generates aura class names for DaisyUI 5.6.
 *
 * Colour (`text-*`) and background (`bg-*`) tints are NOT handled here — they
 * are resolved from the colour constants by the `<Aura>` component, because the
 * `hover` trigger needs to gate the colour on `currentColor`.
 *
 * The animation duration is NOT a class : it is driven by the `--tw-duration`
 * CSS variable, applied as an inline style by the `<Aura>` component (a dynamic
 * `duration-[Nms]` class would never be generated by Tailwind's JIT scanner).
 *
 * @param {Object} [props]
 * @param {Object} [props.after] - Class overrides applied after.
 * @param {Object} [props.before] - Class definitions applied before.
 * @param {string} [props.beforeClassName] - CSS string prepended.
 * @param {string} [props.className] - CSS string appended.
 * @param {AuraSize} [props.size='md'] - Aura size (xs, sm, md, lg, xl).
 * @param {AuraTrigger} [props.trigger='always'] - 'always' (default) or 'hover'.
 * @param {AuraVariant} [props.variant] - Aura style variant.
 *
 * @returns {string} Combined class names.
 *
 * @example
 * ```js
 * getAuraClasses({ variant: 'rainbow', size: 'lg' }) ;
 * // → 'aura aura-rainbow aura-lg'
 *
 * getAuraClasses({ trigger: 'hover' }) ;
 * // → 'aura aura-md [animation-play-state:paused] hover:[animation-play-state:running]'
 * ```
 */
export const getAuraClasses =
({
    after,
    before,
    beforeClassName,
    className,
    size = MD,
    trigger = ALWAYS,
    variant,
}
= {} ) => cn
(
    beforeClassName,
    {
        ...before,

        [ AURA ] : true,

        ...!!variantMap[variant] && { [ variantMap[variant] ] : true },
        ...!!sizeMap[size]       && { [ sizeMap[size]       ] : true },
        ...trigger === HOVER     && { [ AURA_PAUSED ] : true, [ AURA_RUNNING ] : true },

        ...after,
    },
    className,
) ;

export default getAuraClasses ;

/* Tailwind CSS safe list
   `trigger="hover"` restores the light colour on hover via `hover:text-*`, which
   is built at runtime — list the supported colours here so the JIT emits them.
| hover:text-primary | hover:text-secondary    | hover:text-accent  |
| hover:text-neutral | hover:text-info         | hover:text-success |
| hover:text-warning | hover:text-error        | hover:text-inherit |
| hover:text-base-content |
*/
