'use client' ;

import NextLink from 'next/link' ;

import cn from '../../themes/helpers/cn' ;

import
{
    getStepClasses ,
    getStepIconClasses ,
}
from '../../themes/components/step' ;

/** Affordance for a step whose label can be activated. Underlines on hover only. */
const INTERACTIVE = 'link link-hover disabled:cursor-not-allowed disabled:no-underline disabled:opacity-60' ;

/**
 * One node in a {@link Steps} run : a bubble and a label.
 *
 * ### What fills the bubble
 *
 * Three mutually exclusive mechanisms, in DaisyUI's own order of precedence :
 *
 * 1. `icon` — an element that **replaces** the bubble. DaisyUI's selector is
 *    `& > .step-icon, &:not(:has(.step-icon)):after`, so the generated pseudo-element,
 *    and with it the CSS counter, steps aside as soon as an icon is present.
 * 2. `content` — fills `data-content`, which overrides the counter. An empty string is
 *    meaningful: it blanks the bubble.
 * 3. Neither — DaisyUI's CSS counter numbers the step automatically.
 *
 * Because that number is generated by CSS it is neither selectable nor reliably
 * announced. Only the label is real text, so the label has to carry the meaning.
 *
 * @module components/steps/Step
 *
 * @param {Object} props
 * @param {React.ReactNode} [props.children] - Label content. Used when `label` is absent.
 * @param {string} [props.className] - Additional class name on the step.
 * @param {import('../../themes/components/step').StepColor} [props.color] - Step colour. Omit to leave it in its unreached grey.
 * @param {import('../../themes/components/step').StepColor} [props.connectorColor] - Colour of the connector *reaching* this step, independently of `color`. DaisyUI ties the two together, which drops the progress bar back to grey one step early whenever the current step has a colour of its own.
 * @param {string} [props.content] - Bubble content, through `data-content`. An empty string blanks the bubble.
 * @param {boolean} [props.current=false] - Marks the step as the one in progress (`aria-current="step"`).
 * @param {boolean} [props.disabled=false] - Disables the label control, when there is one.
 * @param {string} [props.href] - Renders the label as a `next/link`.
 * @param {React.ReactNode} [props.icon] - Element replacing the bubble.
 * @param {string} [props.iconClassName] - Additional class name on the icon.
 * @param {React.ReactNode} [props.label] - Label content.
 * @param {Function} [props.onClick] - Renders the label as a `<button>`.
 * @param {React.Ref} [props.ref] - Forwarded to the `<li>`.
 *
 * @see https://daisyui.com/components/steps
 *
 * @example
 * ```jsx
 * <Step color="primary" current label="Choisir l'offre" />
 * <Step content="✓" color="success" label="Inscription" />
 * <Step icon={ <CartIcon /> } label="Paiement" />
 * ```
 */
const Step =
({
    children ,
    className ,
    color ,
    connectorColor ,
    content ,
    current = false ,
    disabled = false ,
    href ,
    icon ,
    iconClassName ,
    label ,
    onClick ,
    ref ,
    ...rest
}) =>
{
    const text = label ?? children ;

    const interactive = !disabled && ( !!href || typeof onClick === 'function' ) ;

    let body = text ;

    if ( interactive && href )
    {
        body = (
            <NextLink className={ INTERACTIVE } href={ href } onClick={ onClick }>
                { text }
            </NextLink>
        ) ;
    }
    else if ( href || typeof onClick === 'function' )
    {
        body = (
            <button className={ INTERACTIVE } disabled={ disabled } onClick={ onClick } type="button">
                { text }
            </button>
        ) ;
    }

    return (
        <li
            aria-current = { current ? 'step' : undefined }
            className    = { getStepClasses({ className , color , connectorColor }) }
            data-content = { content }
            ref          = { ref }
            { ...rest }
        >
            { icon ? (
                <span className={ cn( getStepIconClasses() , iconClassName ) }>
                    { icon }
                </span>
            ) : null }

            { body }
        </li>
    ) ;
} ;

Step.displayName = 'Step' ;

export default Step ;
